baseURL = "resume.robertalbus.com"
relativeURLs = true
languageCode = "en-us"
theme = "almeida-cv"
title = "Resume - Robert Albus"

[params]
colorDark = "#2E3532"
colorLight = "#F4F6F5"
colorPageBackground = "#ddd"
colorPrimary = "#7E9181"
colorPrimaryText = "#fff"
colorRightColumnBackground = "#EBECFE"
colorSecondary = "#aaa"
pages = 1
